/* questions-unit3.js — بنك أسئلة الوحدة الثالثة (Role models) للصف الأول الإعدادي.
   140 سؤال اختيار من متعدد + 29 سؤال تصحيح خطأ (بيتصحح تلقائيًا). كل طالب بياخد 30 سؤال عشوائي منهم. */
(() => {
  window.QUESTION_BANK = window.QUESTION_BANK || {};
  window.QUESTION_BANK.unit3 = {
    mcq: [
      {"id": "u3-m001", "type": "mcq", "q": "A ________ is someone people admire and try to copy because they are successful and kind.", "options": ["role model", "stranger", "thief", "driver"], "answer": 0},
      {"id": "u3-m002", "type": "mcq", "q": "Mohamed Salah is a famous sports ________ who inspires millions of young people around the world.", "options": ["fan", "star", "coach", "referee"], "answer": 1},
      {"id": "u3-m003", "type": "mcq", "q": "Good role models always ________ money to charities to support poor children.", "options": ["take", "donate", "steal", "waste"], "answer": 1},
      {"id": "u3-m004", "type": "mcq", "q": "He showed great ________ when he saved the little puppy from the busy street.", "options": ["laziness", "bravery", "fear", "weakness"], "answer": 1},
      {"id": "u3-m005", "type": "mcq", "q": "Our school principal is a ________ man who always makes fair and wise choices.", "options": ["foolish", "sensible", "lazy", "scary"], "answer": 1},
      {"id": "u3-m006", "type": "mcq", "q": "Mo Salah has got a famous ________ on his face that makes everyone feel happy.", "options": ["scarf", "smile", "glasses", "beard"], "answer": 1},
      {"id": "u3-m007", "type": "mcq", "q": "Famous football players have millions of ________ who cheer for them in every match.", "options": ["enemies", "fans", "strangers", "writers"], "answer": 1},
      {"id": "u3-m008", "type": "mcq", "q": "My grandfather is very ________; he always gives gifts to poor people in our village.", "options": ["selfish", "generous", "greedy", "lazy"], "answer": 1},
      {"id": "u3-m009", "type": "mcq", "q": "Sir Magdi Yacoub is a wonderful role model because he treats children with ________ problems.", "options": ["eye", "heart", "hair", "leg"], "answer": 1},
      {"id": "u3-m010", "type": "mcq", "q": "To be an inspiring role model, you should always treat your classmates ________.", "options": ["badly", "politely", "angrily", "loudly"], "answer": 1},
      {"id": "u3-m011", "type": "mcq", "q": "Mohamed Salah ________ got amazing running speed and a very kind heart.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m012", "type": "mcq", "q": "Successful role models ________ got the determination to work hard every day.", "options": ["has", "have", "is", "are"], "answer": 1},
      {"id": "u3-m013", "type": "mcq", "q": "________ your father got books about famous history figures and heroes?", "options": ["Have", "Has", "Is", "Does"], "answer": 1},
      {"id": "u3-m014", "type": "mcq", "q": "We ________ got any time to waste if we want to achieve our big goals.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m015", "type": "mcq", "q": "What special sports skills ________ this dynamic athlete got?", "options": ["has", "have", "does", "is"], "answer": 0},
      {"id": "u3-m016", "type": "mcq", "q": "I ________ got a personal blog, but I have got a small diary to write about heroes.", "options": ["hasn't", "haven't", "don't", "am not"], "answer": 1},
      {"id": "u3-m017", "type": "mcq", "q": "Look! That famous runner ________ got three new gold medals.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m018", "type": "mcq", "q": "________ the students got a clear idea about their future role models?", "options": ["Has", "Have", "Do", "Are"], "answer": 1},
      {"id": "u3-m019", "type": "mcq", "q": "True community leaders ________ got any selfish habits; they love helping.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m020", "type": "mcq", "q": "Writing an essay about your hero is a very inspiring school ________.", "options": ["job", "assignment", "device", "password"], "answer": 1},
      {"id": "u3-m021", "type": "mcq", "q": "Dr. Ahmed Zewail was a ________ Egyptian scientist who won the Nobel Prize.", "options": ["boring", "brilliant", "lazy", "weak"], "answer": 1},
      {"id": "u3-m022", "type": "mcq", "q": "People love my uncle because he has got a very supportive ________.", "options": ["device", "character", "mustache", "smartphone"], "answer": 1},
      {"id": "u3-m023", "type": "mcq", "q": "A person cannot be a good role model if they behave in a ________ way.", "options": ["polite", "rude", "sensible", "generous"], "answer": 1},
      {"id": "u3-m024", "type": "mcq", "q": "The winger scores many goals because he is exceptionally ________ on the pitch.", "options": ["slow", "quick", "weak", "heavy"], "answer": 1},
      {"id": "u3-m025", "type": "mcq", "q": "Learning about successful people helps build our personal ________.", "options": ["fear", "confidence", "device", "routine"], "answer": 1},
      {"id": "u3-m026", "type": "mcq", "q": "They ________ got a digital screen to watch the movie about successful heroes.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m027", "type": "mcq", "q": "________ your English teacher got a favorite character in history?", "options": ["Have", "Has", "Does", "Is"], "answer": 1},
      {"id": "u3-m028", "type": "mcq", "q": "The local medical charity ________ got enough funds to build a new laboratory.", "options": ["has", "have", "is", "does"], "answer": 0},
      {"id": "u3-m029", "type": "mcq", "q": "She ________ got a lot of free time because she trains for six hours a day.", "options": ["hasn't", "haven't", "doesn't", "isn't"], "answer": 0},
      {"id": "u3-m030", "type": "mcq", "q": "What interesting facts ________ you got about Egyptian role models?", "options": ["has", "have", "does", "is"], "answer": 1},
      {"id": "u3-m031", "type": "mcq", "q": "A role model should inspire young people to make a positive ________.", "options": ["problem", "difference", "mistake", "damage"], "answer": 1},
      {"id": "u3-m032", "type": "mcq", "q": "He is a ________ public speaker; everyone learns from his daily advice.", "options": ["bad", "wonderful", "lazy", "scary"], "answer": 1},
      {"id": "u3-m033", "type": "mcq", "q": "My older brother wants to be a ________ engineer like his role model.", "options": ["professional", "traditional", "weak", "careless"], "answer": 0},
      {"id": "u3-m034", "type": "mcq", "q": "Persistence and continuous work are keys to becoming a ________ person.", "options": ["successful", "bad", "lazy", "foolish"], "answer": 0},
      {"id": "u3-m035", "type": "mcq", "q": "The young student was very ________ when he spoke about his mother's hard work.", "options": ["proud", "scared", "lazy", "foolish"], "answer": 0},
      {"id": "u3-m036", "type": "mcq", "q": "Many people admire sports stars who display great sportsmanship and ________.", "options": ["weakness", "kindness", "anger", "laziness"], "answer": 1},
      {"id": "u3-m037", "type": "mcq", "q": "A good citizen always participates in ________ work to help their neighborhood.", "options": ["lazy", "voluntary", "bad", "dangerous"], "answer": 1},
      {"id": "u3-m038", "type": "mcq", "q": "He won an award for his outstanding ________ in the national chess competition.", "options": ["failure", "achievement", "error", "delay"], "answer": 1},
      {"id": "u3-m039", "type": "mcq", "q": "She works as a volunteer at a charity that cares for ________ children.", "options": ["rich", "orphaned", "healthy", "strong"], "answer": 1},
      {"id": "u3-m040", "type": "mcq", "q": "It takes a lot of ________ to keep trying after you fail an exam.", "options": ["laziness", "patience", "fear", "boredom"], "answer": 1},
      {"id": "u3-m041", "type": "mcq", "q": "My cousin ________ got long curly hair and beautiful green eyes.", "options": ["have", "has", "is", "are"], "answer": 1},
      {"id": "u3-m042", "type": "mcq", "q": "The players ________ got their new sports kits for the final match today.", "options": ["has", "have", "do", "are"], "answer": 1},
      {"id": "u3-m043", "type": "mcq", "q": "________ your mother got a special recipe book for healthy meals?", "options": ["Have", "Has", "Is", "Does"], "answer": 1},
      {"id": "u3-m044", "type": "mcq", "q": "We ________ got any online classes during the weekend mornings.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m045", "type": "mcq", "q": "What talents ________ your best friend got?", "options": ["has", "have", "does", "is"], "answer": 0},
      {"id": "u3-m046", "type": "mcq", "q": "I ________ got a digital camera, but I can take good photos with my phone.", "options": ["hasn't", "haven't", "don't", "am not"], "answer": 1},
      {"id": "u3-m047", "type": "mcq", "q": "Look! That tall player ________ got the ability to jump very high.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m048", "type": "mcq", "q": "________ the volunteers got a clear plan to clean the public park today?", "options": ["Has", "Have", "Do", "Are"], "answer": 1},
      {"id": "u3-m049", "type": "mcq", "q": "True heroes ________ got any greedy thoughts; they work for their country.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m050", "type": "mcq", "q": "Discussing role models in class gives us a lot of positive ________.", "options": ["energy", "boredom", "problems", "errors"], "answer": 0},
      {"id": "u3-m051", "type": "mcq", "q": "He is a very ________ person; he always comes on time and never breaks a promise.", "options": ["unreliable", "reliable", "lazy", "careless"], "answer": 1},
      {"id": "u3-m052", "type": "mcq", "q": "The charity organization helps to ________ money for poor families.", "options": ["drop", "raise", "lose", "waste"], "answer": 1},
      {"id": "u3-m053", "type": "mcq", "q": "Mo Salah is a role model because he never gives up and always stays ________.", "options": ["negative", "positive", "lazy", "rude"], "answer": 1},
      {"id": "u3-m054", "type": "mcq", "q": "The young scientist made a great ________ to the field of digital medicine.", "options": ["mistake", "contribution", "damage", "error"], "answer": 1},
      {"id": "u3-m055", "type": "mcq", "q": "To achieve your dreams, you must have a strong ________.", "options": ["weakness", "will", "fear", "laziness"], "answer": 1},
      {"id": "u3-m056", "type": "mcq", "q": "The teacher praised the student for his ________ answers in the quiz.", "options": ["foolish", "intelligent", "wrong", "bad"], "answer": 1},
      {"id": "u3-m057", "type": "mcq", "q": "My uncle ________ got a thick black mustache and brown eyes.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m058", "type": "mcq", "q": "They ________ got many fans because they play music beautifully.", "options": ["has", "have", "do", "are"], "answer": 1},
      {"id": "u3-m059", "type": "mcq", "q": "________ your sister got a collection of stories about brave women?", "options": ["Have", "Has", "Is", "Does"], "answer": 1},
      {"id": "u3-m060", "type": "mcq", "q": "We ________ got any sports training on heavy rainy days.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m061", "type": "mcq", "q": "What goals ________ the team got for the next digital tournament?", "options": ["has", "have", "does", "is"], "answer": 0},
      {"id": "u3-m062", "type": "mcq", "q": "I ________ got a laptop, but my brother has got a powerful desktop PC.", "options": ["hasn't", "haven't", "don't", "am not"], "answer": 1},
      {"id": "u3-m063", "type": "mcq", "q": "Look! The champion ________ got the gold cup in his hands.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m064", "type": "mcq", "q": "________ the participants got their identification cards for the workshop?", "options": ["Has", "Have", "Do", "Are"], "answer": 1},
      {"id": "u3-m065", "type": "mcq", "q": "Great role models ________ got any time for spreading negative thoughts.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m066", "type": "mcq", "q": "Being polite to elderly people is a sign of a good ________.", "options": ["error", "character", "mistake", "device"], "answer": 1},
      {"id": "u3-m067", "type": "mcq", "q": "She loves reading biographies to learn about the lives of ________ figures.", "options": ["boring", "historical", "lazy", "weak"], "answer": 1},
      {"id": "u3-m068", "type": "mcq", "q": "The courageous firefighter received a medal for his extreme ________.", "options": ["cowardice", "bravery", "laziness", "fear"], "answer": 1},
      {"id": "u3-m069", "type": "mcq", "q": "He is a very ________ student; he spends hours studying in the library.", "options": ["lazy", "hard-working", "careless", "foolish"], "answer": 1},
      {"id": "u3-m070", "type": "mcq", "q": "My role model always encourages me to develop my mental ________.", "options": ["weaknesses", "skills", "errors", "problems"], "answer": 1},
      {"id": "u3-m071", "type": "mcq", "q": "A ________ person always respects others and uses good manners online and offline.", "options": ["rude", "polite", "lazy", "scary"], "answer": 1},
      {"id": "u3-m072", "type": "mcq", "q": "Mohamed Salah is known for his great ________; he can run across the pitch very fast.", "options": ["height", "speed", "hair", "weight"], "answer": 1},
      {"id": "u3-m073", "type": "mcq", "q": "Good role models always ________ money to charities to build hospitals.", "options": ["take", "donate", "steal", "waste"], "answer": 1},
      {"id": "u3-m074", "type": "mcq", "q": "The young girl showed great ________ when she gave a speech in front of thousands.", "options": ["laziness", "confidence", "fear", "weakness"], "answer": 1},
      {"id": "u3-m075", "type": "mcq", "q": "Sir Magdi Yacoub is a wonderful role model because he helps children with ________ problems.", "options": ["eye", "heart", "hair", "leg"], "answer": 1},
      {"id": "u3-m076", "type": "mcq", "q": "Famous sports stars have millions of ________ who follow them on social media.", "options": ["enemies", "fans", "strangers", "writers"], "answer": 1},
      {"id": "u3-m077", "type": "mcq", "q": "My older brother is very ________; he always helps my parents with heavy tasks.", "options": ["selfish", "helpful", "greedy", "lazy"], "answer": 1},
      {"id": "u3-m078", "type": "mcq", "q": "Hard work and determination are keys to becoming a ________ person in life.", "options": ["successful", "bad", "lazy", "foolish"], "answer": 0},
      {"id": "u3-m079", "type": "mcq", "q": "The young boy was very ________ when his father won the ideal teacher award.", "options": ["proud", "scared", "lazy", "foolish"], "answer": 0},
      {"id": "u3-m080", "type": "mcq", "q": "A good leader inspires people to make a positive ________ in the community.", "options": ["problem", "difference", "mistake", "damage"], "answer": 1},
      {"id": "u3-m081", "type": "mcq", "q": "My best friend ________ got short curly hair and brown eyes.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m082", "type": "mcq", "q": "Successful athletes ________ got the ability to train hard every single day.", "options": ["has", "have", "is", "are"], "answer": 1},
      {"id": "u3-m083", "type": "mcq", "q": "________ your cousin got a notebook to write about his role models?", "options": ["Have", "Has", "Is", "Does"], "answer": 1},
      {"id": "u3-m084", "type": "mcq", "q": "We ________ got any doubt that hard work leads to high marks.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m085", "type": "mcq", "q": "What features ________ a true hero got?", "options": ["has", "have", "does", "is"], "answer": 0},
      {"id": "u3-m086", "type": "mcq", "q": "I ________ got a digital tablet, but I have got a smartphone to study.", "options": ["hasn't", "haven't", "don't", "am not"], "answer": 1},
      {"id": "u3-m087", "type": "mcq", "q": "Look! That famous scientist ________ got a new award for his research.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m088", "type": "mcq", "q": "________ the children got a clear presentation about role models today?", "options": ["Has", "Have", "Do", "Are"], "answer": 1},
      {"id": "u3-m089", "type": "mcq", "q": "True role models ________ got any rude habits; they speak politely.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m090", "type": "mcq", "q": "Learning about successful figures gives us a lot of positive ________.", "options": ["energy", "boredom", "problems", "errors"], "answer": 0},
      {"id": "u3-m091", "type": "mcq", "q": "He is a very ________ player; he always passes the ball to his teammates.", "options": ["selfish", "unselfish", "lazy", "rude"], "answer": 1},
      {"id": "u3-m092", "type": "mcq", "q": "The local charity organization helps to ________ funds for poor families.", "options": ["drop", "raise", "lose", "waste"], "answer": 1},
      {"id": "u3-m093", "type": "mcq", "q": "Dr. Ahmed Zewail was a ________ scientist who changed the world.", "options": ["boring", "brilliant", "lazy", "weak"], "answer": 1},
      {"id": "u3-m094", "type": "mcq", "q": "People love my grandmother because she has got a very kind ________.", "options": ["device", "character", "mustache", "smartphone"], "answer": 1},
      {"id": "u3-m095", "type": "mcq", "q": "Being dynamic and active helps athletes achieve their ________ quickly.", "options": ["mistakes", "goals", "devices", "planners"], "answer": 1},
      {"id": "u3-m096", "type": "mcq", "q": "They ________ got an interactive screen to watch the documentary about heroes.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m097", "type": "mcq", "q": "________ your uncle got a black beard and a mustache?", "options": ["Have", "Has", "Does", "Is"], "answer": 1},
      {"id": "u3-m098", "type": "mcq", "q": "The charity association ________ got enough books for the village library.", "options": ["has", "have", "is", "does"], "answer": 0},
      {"id": "u3-m099", "type": "mcq", "q": "She ________ got a lot of free time because she does voluntary work every day.", "options": ["hasn't", "haven't", "doesn't", "isn't"], "answer": 0},
      {"id": "u3-m100", "type": "mcq", "q": "What interesting stories ________ you got about successful doctors?", "options": ["has", "have", "does", "is"], "answer": 1},
      {"id": "u3-m101", "type": "mcq", "q": "A role model should treat everyone with deep ________ and appreciation.", "options": ["rudeness", "respect", "anger", "laziness"], "answer": 1},
      {"id": "u3-m102", "type": "mcq", "q": "He is a ________ writer; his books inspire thousands of young children.", "options": ["bad", "wonderful", "lazy", "scary"], "answer": 1},
      {"id": "u3-m103", "type": "mcq", "q": "My cousin wants to be a ________ teacher like his primary school role model.", "options": ["professional", "traditional", "weak", "careless"], "answer": 0},
      {"id": "u3-m104", "type": "mcq", "q": "Patience is a vital ________ that every good role model should have.", "options": ["device", "quality", "password", "break"], "answer": 1},
      {"id": "u3-m105", "type": "mcq", "q": "The player was very ________ when he missed the penalty kick on the pitch.", "options": ["happy", "disappointed", "proud", "creative"], "answer": 1},
      {"id": "u3-m106", "type": "mcq", "q": "We ________ got enough funds to complete the charity project this week.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m107", "type": "mcq", "q": "________ your father got a laptop with a fast internet connection?", "options": ["Have", "Has", "Does", "Is"], "answer": 1},
      {"id": "u3-m108", "type": "mcq", "q": "The new school labs ________ got highly interactive digital tablets.", "options": ["has", "have", "is", "does"], "answer": 1},
      {"id": "u3-m109", "type": "mcq", "q": "She ________ got straight hair; her hair is short, dark, and very curly.", "options": ["hasn't", "haven't", "doesn't", "isn't"], "answer": 0},
      {"id": "u3-m110", "type": "mcq", "q": "What items ________ you got inside your school sports bag?", "options": ["has", "have", "does", "is"], "answer": 1},
      {"id": "u3-m111", "type": "mcq", "q": "Doing voluntary work is an excellent ________ that helps the community.", "options": ["device", "habit", "password", "break"], "answer": 1},
      {"id": "u3-m112", "type": "mcq", "q": "A sensible person always thinks carefully before making ________.", "options": ["choices", "mistakes", "errors", "problems"], "answer": 0},
      {"id": "u3-m113", "type": "mcq", "q": "The famous sports star is exceptionally ________ to his young fans.", "options": ["rude", "kind", "lazy", "careless"], "answer": 1},
      {"id": "u3-m114", "type": "mcq", "q": "To become a professional developer, you need to develop your digital ________.", "options": ["weaknesses", "skills", "errors", "breaks"], "answer": 1},
      {"id": "u3-m115", "type": "mcq", "q": "Look! The champion ________ got the gold medal around his neck.", "options": ["have", "has", "is", "does"], "answer": 1},
      {"id": "u3-m116", "type": "mcq", "q": "My friends ________ currently writing a blog post about their favorite role models.", "options": ["do", "does", "is", "are"], "answer": 3},
      {"id": "u3-m117", "type": "mcq", "q": "A lazy student ________ achieves his academic goals successfully.", "options": ["always", "never", "usually", "often"], "answer": 1},
      {"id": "u3-m118", "type": "mcq", "q": "We shouldn't become completely dependent ________ digital apps for our learning.", "options": ["on", "at", "in", "for"], "answer": 0},
      {"id": "u3-m119", "type": "mcq", "q": "To log into your educational platform, you must enter your user ________.", "options": ["postcard", "password", "picture", "printer"], "answer": 1},
      {"id": "u3-m120", "type": "mcq", "q": "Clicking on unknown links can ________ the software of your smart device.", "options": ["fix", "harm", "help", "charge"], "answer": 1},
      {"id": "u3-m121", "type": "mcq", "q": "The phrase \"have got\" means that you own or ________ something.", "options": ["lose", "possess", "take", "do"], "answer": 1},
      {"id": "u3-m122", "type": "mcq", "q": "\"Frightened\" has a very close meaning to the word ________.", "options": ["happy", "scared", "brave", "angry"], "answer": 1},
      {"id": "u3-m123", "type": "mcq", "q": "A printer is used to make ________ copies of digital text files.", "options": ["electronic", "paper", "sound", "video"], "answer": 1},
      {"id": "u3-m124", "type": "mcq", "q": "To select a specific file on a smartphone, you must ________ the icon.", "options": ["click", "tap", "type", "cut"], "answer": 1},
      {"id": "u3-m125", "type": "mcq", "q": "A digital mind map is a modern tool used to organize your ________.", "options": ["clothes", "ideas", "chargers", "passwords"], "answer": 1},
      {"id": "u3-m126", "type": "mcq", "q": "Group workshops ________ enhance collaboration between school pupils.", "options": ["always", "doesn't", "isn't", "aren't"], "answer": 0},
      {"id": "u3-m127", "type": "mcq", "q": "Look! The volunteers ________ in pairs to clean the neighborhood now.", "options": ["work", "are working", "works", "worked"], "answer": 1},
      {"id": "u3-m128", "type": "mcq", "q": "My father ________ checks his digital planner to organize his timeline.", "options": ["always", "never", "are", "is"], "answer": 0},
      {"id": "u3-m129", "type": "mcq", "q": "Does this modern device ________ a fast battery charger?", "options": ["have", "has", "having", "is having"], "answer": 0},
      {"id": "u3-m130", "type": "mcq", "q": "A clever learner ________ forgets to review his final text summary.", "options": ["never", "always", "usually", "often"], "answer": 0},
      {"id": "u3-m131", "type": "mcq", "q": "We use the present simple tense to describe regular ________ and habits.", "options": ["routines", "temporary actions", "past events", "future continuous"], "answer": 0},
      {"id": "u3-m132", "type": "mcq", "q": "The key phrase \"at present\" indicates that the action is ________.", "options": ["finished", "continuous", "a habit", "past"], "answer": 1},
      {"id": "u3-m133", "type": "mcq", "q": "Water ________ at 100 degrees Celsius under normal natural conditions.", "options": ["boil", "boils", "is boiling", "boiling"], "answer": 1},
      {"id": "u3-m134", "type": "mcq", "q": "What ________ your brother looking up in the online dictionary right now?", "options": ["does", "is", "do", "are"], "answer": 1},
      {"id": "u3-m135", "type": "mcq", "q": "Modern pupils ________ like using slow and boring learning methods.", "options": ["doesn't", "don't", "aren't", "isn't"], "answer": 1},
      {"id": "u3-m136", "type": "mcq", "q": "I ________ create a secure backup for my files to keep them safe.", "options": ["usually", "never", "rarely", "no"], "answer": 0},
      {"id": "u3-m137", "type": "mcq", "q": "Interactive boards ________ display videos and text smoothly in class.", "options": ["always", "doesn't", "isn't", "aren't"], "answer": 0},
      {"id": "u3-m138", "type": "mcq", "q": "Look! The child ________ an e-book about Mohamed Salah at this moment.", "options": ["reads", "is reading", "read", "reading"], "answer": 1},
      {"id": "u3-m139", "type": "mcq", "q": "My older cousins ________ got short curly hair; they have straight hair.", "options": ["hasn't", "haven't", "don't", "aren't"], "answer": 1},
      {"id": "u3-m140", "type": "mcq", "q": "Always check the privacy settings before you share photos with ________ online.", "options": ["parents", "strangers", "teachers", "relatives"], "answer": 1},
    ],
    correction: [
      {"id": "u3-c01", "type": "correction", "sentence": "My role model have got a very successful life.", "wrong": "have", "answers": ["has"]},
      {"id": "u3-c02", "type": "correction", "sentence": "They hasn't got any ideas for the charity project.", "wrong": "hasn't", "answers": ["haven't"]},
      {"id": "u3-c03", "type": "correction", "sentence": "Does you got a book about Mohamed Salah?", "wrong": "Does", "answers": ["Have"]},
      {"id": "u3-c04", "type": "correction", "sentence": "He has get a prize for his brilliant scientific research.", "wrong": "get", "answers": ["got"]},
      {"id": "u3-c05", "type": "correction", "sentence": "We haven't get enough information about this star.", "wrong": "get", "answers": ["got"]},
      {"id": "u3-c06", "type": "correction", "sentence": "A selfish person makes an excellent role model.", "wrong": "selfish", "answers": ["generous", "unselfish", "kind", "polite", "caring", "helpful", "honest", "good"]},
      {"id": "u3-c07", "type": "correction", "sentence": "He donates his clothes to make poor people sad.", "wrong": "sad", "answers": ["happy", "glad", "pleased", "comfortable", "warm"]},
      {"id": "u3-c08", "type": "correction", "sentence": "A child with bad manners always speaks politely to everyone.", "wrong": "politely", "answers": ["rudely", "impolitely", "badly"]},
      {"id": "u3-c09", "type": "correction", "sentence": "The famous coach is very weak; he can lift heavy weights easily.", "wrong": "weak", "answers": ["strong", "powerful", "fit", "muscular"]},
      {"id": "u3-c10", "type": "correction", "sentence": "Lazy people always achieve their big goals quickly.", "wrong": "Lazy", "answers": ["Hard-working", "Hardworking", "Determined", "Active", "Diligent", "Persistent"]},
      {"id": "u3-c11", "type": "correction", "sentence": "Has the sports stars got many fans in Egypt?", "wrong": "Has", "answers": ["Have"]},
      {"id": "u3-c12", "type": "correction", "sentence": "I has got deep respect for my hard-working teachers.", "wrong": "has", "answers": ["have"]},
      {"id": "u3-c13", "type": "correction", "sentence": "What has you got in your project plan about heroes?", "wrong": "has", "answers": ["have"]},
      {"id": "u3-c14", "type": "correction", "sentence": "She hasn't got some awards for her creative drawings.", "wrong": "some", "answers": ["any"]},
      {"id": "u3-c15", "type": "correction", "sentence": "Role models are people who always does good things.", "wrong": "does", "answers": ["do"]},
      {"id": "u3-c16", "type": "correction", "sentence": "My friends has got a great plan to do voluntary work.", "wrong": "has", "answers": ["have"]},
      {"id": "u3-c17", "type": "correction", "sentence": "Look! The teacher is explain how to choose a good role model.", "wrong": "explain", "answers": ["explaining"]},
      {"id": "u3-c18", "type": "correction", "sentence": "Does you know the name of this brilliant scientist?", "wrong": "Does", "answers": ["Do"]},
      {"id": "u3-c19", "type": "correction", "sentence": "He don't like participating in voluntary work.", "wrong": "don't", "answers": ["doesn't", "does not"]},
      {"id": "u3-c20", "type": "correction", "sentence": "She donates her money at the moment.", "wrong": "donates", "answers": ["is donating"]},
      {"id": "u3-c21", "type": "correction", "sentence": "We goes to the charity association every Friday morning.", "wrong": "goes", "answers": ["go"]},
      {"id": "u3-c22", "type": "correction", "sentence": "How much times a week do you train on the pitch?", "wrong": "much", "answers": ["many"]},
      {"id": "u3-c23", "type": "correction", "sentence": "Listen! The children are laugh loudly with their coach.", "wrong": "laugh", "answers": ["laughing"]},
      {"id": "u3-c24", "type": "correction", "sentence": "My father never are late for his primary school classes.", "wrong": "are", "answers": ["is"]},
      {"id": "u3-c25", "type": "correction", "sentence": "Are you watch a documentary about Mo Salah right now?", "wrong": "watch", "answers": ["watching"]},
      {"id": "u3-c26", "type": "correction", "sentence": "A charger is used to make copies of documents on paper.", "wrong": "charger", "answers": ["printer"]},
      {"id": "u3-c27", "type": "correction", "sentence": "Tap on the laptop mouse to select the dynamic file icon.", "wrong": "Tap", "answers": ["Click"]},
      {"id": "u3-c28", "type": "correction", "sentence": "I don't knows the password to open my personal planner.", "wrong": "knows", "answers": ["know"]},
      {"id": "u3-c29", "type": "correction", "sentence": "They plays sports in the playground every Saturday morning.", "wrong": "plays", "answers": ["play"]},
    ],
  };
})();
