/* questions-unit2.js — بنك أسئلة الوحدة الثانية (Learning to learn) للصف الأول الإعدادي.
   140 سؤال اختيار من متعدد + 30 سؤال تصحيح خطأ (بيتصحح تلقائيًا). كل طالب بياخد 30 سؤال عشوائي منهم. */
(() => {
  window.QUESTION_BANK = window.QUESTION_BANK || {};
  window.QUESTION_BANK.unit2 = {
    mcq: [
      {"id": "u2-m001", "type": "mcq", "q": "To improve your text comprehension, you should read the passage ________.", "options": ["quickly", "carefully", "loudly", "badly"], "answer": 1},
      {"id": "u2-m002", "type": "mcq", "q": "A good student uses different learning ________ to understand difficult lessons.", "options": ["devices", "strategies", "toys", "habits"], "answer": 1},
      {"id": "u2-m003", "type": "mcq", "q": "Creating a ________ map is an excellent way to organize your ideas visually.", "options": ["mind", "body", "street", "digital"], "answer": 0},
      {"id": "u2-m004", "type": "mcq", "q": "When you don't know the meaning of a word, you should look it up in a ________.", "options": ["notebook", "dictionary", "timetable", "blog"], "answer": 1},
      {"id": "u2-m005", "type": "mcq", "q": "Active learning means that you ________ in classroom discussions.", "options": ["sleep", "participate", "forget", "leave"], "answer": 1},
      {"id": "u2-m006", "type": "mcq", "q": "Making errors is a natural part of the learning ________; we learn from them.", "options": ["routine", "process", "device", "break"], "answer": 1},
      {"id": "u2-m007", "type": "mcq", "q": "Good learners always take useful ________ while the teacher is explaining.", "options": ["photos", "notes", "games", "rewards"], "answer": 1},
      {"id": "u2-m008", "type": "mcq", "q": "Self-________ helps you check your own progress and know your weak points.", "options": ["assessment", "assignment", "device", "password"], "answer": 0},
      {"id": "u2-m009", "type": "mcq", "q": "Working in pairs helps students to ________ ideas and learn from each other.", "options": ["hide", "exchange", "waste", "lose"], "answer": 1},
      {"id": "u2-m010", "type": "mcq", "q": "A ________ study space without noise is essential for deep concentration.", "options": ["loud", "quiet", "dangerous", "dirty"], "answer": 1},
      {"id": "u2-m011", "type": "mcq", "q": "This is my ________ desk; she always keeps her pens organized.", "options": ["sister's", "sister", "sisters'", "sisters"], "answer": 0},
      {"id": "u2-m012", "type": "mcq", "q": "The ________ books are on the big table in the staff room. (many teachers)", "options": ["teacher's", "teachers'", "teachers", "teacher"], "answer": 1},
      {"id": "u2-m013", "type": "mcq", "q": "We need to follow the ________ advice to get high marks in the exam. (one expert)", "options": ["expert's", "experts", "experts'", "expert"], "answer": 0},
      {"id": "u2-m014", "type": "mcq", "q": "Those are the ________ computers. They use them in the digital lab.", "options": ["boys'", "boy's", "boys", "boy"], "answer": 0},
      {"id": "u2-m015", "type": "mcq", "q": "Whose summary is this? - It's ________.", "options": ["Amers", "Amer's", "Amers'", "Amer"], "answer": 1},
      {"id": "u2-m016", "type": "mcq", "q": "The ________ classroom is next to ours; they are very noisy today.", "options": ["girls'", "girl's", "girls", "girl"], "answer": 0},
      {"id": "u2-m017", "type": "mcq", "q": "This is the ________ cover. It is made of strong blue plastic.", "options": ["dictionary's", "dictionary", "dictionaries'", "dictionaries"], "answer": 0},
      {"id": "u2-m018", "type": "mcq", "q": "The ________ library is open for all students during the school day.", "options": ["school's", "school", "schools'", "schools"], "answer": 0},
      {"id": "u2-m019", "type": "mcq", "q": "We found the ________ keys left in the science laboratory. (one professor)", "options": ["professor's", "professors", "professors'", "professor"], "answer": 0},
      {"id": "u2-m020", "type": "mcq", "q": "These are the ________ tools. They are testing the new school app.", "options": ["developers'", "developer's", "developers", "developer"], "answer": 0},
      {"id": "u2-m021", "type": "mcq", "q": "Setting clear ________ helps you focus on what you want to achieve.", "options": ["mistakes", "goals", "devices", "passwords"], "answer": 1},
      {"id": "u2-m022", "type": "mcq", "q": "________ learning allows you to study online from any place you like.", "options": ["Traditional", "Distance", "Slow", "Bad"], "answer": 1},
      {"id": "u2-m023", "type": "mcq", "q": "It is helpful to ________ what you have learned to check your memory.", "options": ["forget", "review", "drop", "lose"], "answer": 1},
      {"id": "u2-m024", "type": "mcq", "q": "Critical ________ is a skill that helps you analyze information logically.", "options": ["thinking", "sleeping", "running", "playing"], "answer": 0},
      {"id": "u2-m025", "type": "mcq", "q": "The ________ locker is full of books and maps. (Belonging to two students)", "options": ["students'", "student's", "students", "student"], "answer": 0},
      {"id": "u2-m026", "type": "mcq", "q": "I can't find the ________ page. It is torn out of the book.", "options": ["notebook's", "notebook", "notebooks'", "notebooks"], "answer": 0},
      {"id": "u2-m027", "type": "mcq", "q": "These are the ________ results. They both got the full mark.", "options": ["twins'", "twin's", "twins", "twin"], "answer": 0},
      {"id": "u2-m028", "type": "mcq", "q": "Regular practice is the best way to develop your mental ________.", "options": ["tools", "skills", "devices", "routines"], "answer": 1},
      {"id": "u2-m029", "type": "mcq", "q": "An interactive ________ helps students collaborate during the project.", "options": ["workshop", "routine", "break", "device"], "answer": 0},
      {"id": "u2-m030", "type": "mcq", "q": "How do you prepare for exams? - By making a study ________.", "options": ["timetable", "game", "selfie", "password"], "answer": 0},
      {"id": "u2-m031", "type": "mcq", "q": "Group work encourages students to show respect for others' ________.", "options": ["opinions", "clothes", "devices", "errors"], "answer": 0},
      {"id": "u2-m032", "type": "mcq", "q": "The primary school ________ is explaining the new learning strategies.", "options": ["headteacher", "doctor", "driver", "player"], "answer": 0},
      {"id": "u2-m033", "type": "mcq", "q": "These are the ________ research papers. They are university professors.", "options": ["men's", "mens'", "men", "mens"], "answer": 0},
      {"id": "u2-m034", "type": "mcq", "q": "My ________ advice always helps me solve difficult mathematical problems.", "options": ["father's", "fathers'", "father", "fathers"], "answer": 0},
      {"id": "u2-m035", "type": "mcq", "q": "The ________ screen is highly interactive.", "options": ["laptop's", "laptop", "laptops'", "laptops"], "answer": 0},
      {"id": "u2-m036", "type": "mcq", "q": "When you summarize a paragraph, you should only write the ________ ideas.", "options": ["minor", "main", "wrong", "continuous"], "answer": 1},
      {"id": "u2-m037", "type": "mcq", "q": "Highlighting keywords is a helpful ________ to remember historical dates.", "options": ["mistake", "technique", "break", "password"], "answer": 1},
      {"id": "u2-m038", "type": "mcq", "q": "Students should test their ________ by solving quizzes after studying.", "options": ["clothes", "knowledge", "devices", "secrets"], "answer": 1},
      {"id": "u2-m039", "type": "mcq", "q": "The teacher asked us to work in ________ to complete the dialogue together.", "options": ["pairs", "single", "alone", "rows"], "answer": 0},
      {"id": "u2-m040", "type": "mcq", "q": "To make your handwriting better, you need to ________ every day.", "options": ["forget", "practice", "sleep", "drop"], "answer": 1},
      {"id": "u2-m041", "type": "mcq", "q": "Good learners don't give up when they find a topic ________.", "options": ["easy", "challenging", "simple", "short"], "answer": 1},
      {"id": "u2-m042", "type": "mcq", "q": "Using a digital ________ can help you manage your study hours efficiently.", "options": ["toy", "planner", "uniform", "key"], "answer": 1},
      {"id": "u2-m043", "type": "mcq", "q": "Students need to receive regular ________ from teachers to correct their mistakes.", "options": ["feedback", "games", "snacks", "chargers"], "answer": 0},
      {"id": "u2-m044", "type": "mcq", "q": "Asking questions in class shows that you are an ________ learner.", "options": ["lazy", "active", "inactive", "asleep"], "answer": 1},
      {"id": "u2-m045", "type": "mcq", "q": "This is the ________ office; he helps all students with their digital tablets.", "options": ["supervisor's", "supervisor", "supervisors'", "supervisors"], "answer": 0},
      {"id": "u2-m046", "type": "mcq", "q": "The ________ notebooks are scattered on the floor. (Belonging to the three girls)", "options": ["girl's", "girls'", "girls", "girl"], "answer": 1},
      {"id": "u2-m047", "type": "mcq", "q": "We found the ________ locker unlocked in the changing room. (belonging to several players)", "options": ["players'", "player's", "players", "player"], "answer": 0},
      {"id": "u2-m048", "type": "mcq", "q": "Whose project is this? - It's ________.", "options": ["Faridas", "Farida's", "Faridas'", "Farida"], "answer": 1},
      {"id": "u2-m049", "type": "mcq", "q": "The ________ tools are kept in the science garden shed. (one gardener)", "options": ["gardener's", "gardeners", "gardeners'", "gardener"], "answer": 0},
      {"id": "u2-m050", "type": "mcq", "q": "I really like my ________ style of explaining difficult grammar rules.", "options": ["teacher's", "teachers'", "teachers", "teacher"], "answer": 0},
      {"id": "u2-m051", "type": "mcq", "q": "The ________ department is on the third floor of the school.", "options": ["women's", "womens'", "women", "womens"], "answer": 0},
      {"id": "u2-m052", "type": "mcq", "q": "This is the ________ handle. Please, turn it gently.", "options": ["door's", "door", "doors'", "doors"], "answer": 0},
      {"id": "u2-m053", "type": "mcq", "q": "We need to replace the ________ leg because it cannot stand straight.", "options": ["desk's", "desk", "desks'", "desks"], "answer": 0},
      {"id": "u2-m054", "type": "mcq", "q": "Those are the ________ bags. They left them after the football match.", "options": ["boys'", "boy's", "boys", "boy"], "answer": 0},
      {"id": "u2-m055", "type": "mcq", "q": "My ________ house has a big garage for their cars.", "options": ["uncles'", "uncle's", "uncles", "uncle"], "answer": 0},
      {"id": "u2-m056", "type": "mcq", "q": "Is this ________ smartphone? - Yes, he bought it last week.", "options": ["Youssef's", "Youssef", "Youssefs'", "Youssefs"], "answer": 0},
      {"id": "u2-m057", "type": "mcq", "q": "The ________ laboratory is filled with modern scientific equipment.", "options": ["school's", "school", "schools'", "schools"], "answer": 0},
      {"id": "u2-m058", "type": "mcq", "q": "Learning how to manage your time is a vital life ________ for all students.", "options": ["device", "skill", "break", "password"], "answer": 1},
      {"id": "u2-m059", "type": "mcq", "q": "Group discussions help us see a problem from different ________.", "options": ["screens", "perspectives", "habits", "errors"], "answer": 1},
      {"id": "u2-m060", "type": "mcq", "q": "I need a new cover for my English ________.", "options": ["notebook's", "notebook", "notebooks'", "notebooks"], "answer": 1},
      {"id": "u2-m061", "type": "mcq", "q": "The ________ toys are always organized in the kindergarten.", "options": ["children's", "childrens'", "children", "childrens"], "answer": 0},
      {"id": "u2-m062", "type": "mcq", "q": "An online ________ allows students to share digital resources instantly.", "options": ["platform", "room", "routine", "break"], "answer": 0},
      {"id": "u2-m063", "type": "mcq", "q": "Students shouldn't feel ashamed of their ________; they are opportunities to learn.", "options": ["skills", "errors", "rewards", "goals"], "answer": 1},
      {"id": "u2-m064", "type": "mcq", "q": "That is the ________ staff room. They are discussing the new curriculum.", "options": ["teachers'", "teacher's", "teachers", "teacher"], "answer": 0},
      {"id": "u2-m065", "type": "mcq", "q": "My ________ office is very close to our school building. (one cousin)", "options": ["cousin's", "cousins'", "cousin", "cousins"], "answer": 0},
      {"id": "u2-m066", "type": "mcq", "q": "Self-reliance means you become independent in your learning ________.", "options": ["process", "break", "device", "password"], "answer": 0},
      {"id": "u2-m067", "type": "mcq", "q": "We have a short ________ between the third and fourth lessons to refresh.", "options": ["exam", "break", "routine", "timetable"], "answer": 1},
      {"id": "u2-m068", "type": "mcq", "q": "This is ________ digital tablet. She uses it for distance learning.", "options": ["Soha's", "Soha", "Sohas'", "Sohas"], "answer": 0},
      {"id": "u2-m069", "type": "mcq", "q": "The ________ wheels need to be checked before the school trip. (one bus)", "options": ["bus's", "bus", "buses'", "buses"], "answer": 0},
      {"id": "u2-m070", "type": "mcq", "q": "A digital mind map helps you link different ________ together.", "options": ["concepts", "clothes", "chargers", "mice"], "answer": 0},
      {"id": "u2-m071", "type": "mcq", "q": "To understand a long text, it is useful to write a short ________ of the main points.", "options": ["device", "summary", "password", "break"], "answer": 1},
      {"id": "u2-m072", "type": "mcq", "q": "Sharing your ideas with your classmate means you are working in ________.", "options": ["pairs", "single", "alone", "row"], "answer": 0},
      {"id": "u2-m073", "type": "mcq", "q": "A ________ map is a visual diagram that helps you connect school topics together.", "options": ["street", "body", "mind", "digital"], "answer": 2},
      {"id": "u2-m074", "type": "mcq", "q": "When you don't know the definition of an English word, check a ________.", "options": ["timetable", "notebook", "dictionary", "blog"], "answer": 2},
      {"id": "u2-m075", "type": "mcq", "q": "Students should always learn how to analyze information using critical ________.", "options": ["sleeping", "thinking", "running", "playing"], "answer": 1},
      {"id": "u2-m076", "type": "mcq", "q": "Making mistakes is a useful part of the learning ________ for everyone.", "options": ["process", "routine", "device", "break"], "answer": 0},
      {"id": "u2-m077", "type": "mcq", "q": "Good students always take down ________ during the teacher's explanation.", "options": ["photos", "notes", "games", "rewards"], "answer": 1},
      {"id": "u2-m078", "type": "mcq", "q": "Self-________ allows you to find your own mistakes and improve them.", "options": ["assessment", "assignment", "device", "charger"], "answer": 0},
      {"id": "u2-m079", "type": "mcq", "q": "We should look at our school ________ to know which subject is next.", "options": ["notebook", "timetable", "library", "dictionary"], "answer": 1},
      {"id": "u2-m080", "type": "mcq", "q": "A quiet ________ is very important if you want to concentrate on your homework.", "options": ["environment", "device", "mistake", "error"], "answer": 0},
      {"id": "u2-m081", "type": "mcq", "q": "This is my ________ notebook; she lent it to me to copy the summary.", "options": ["sister's", "sister", "sisters'", "sisters"], "answer": 0},
      {"id": "u2-m082", "type": "mcq", "q": "The ________ laboratory coats are kept clean in the changing room. (many scientists)", "options": ["scientists'", "scientist's", "scientists", "scientist"], "answer": 0},
      {"id": "u2-m083", "type": "mcq", "q": "We must listen to our ________ instructions during the digital project. (several experts)", "options": ["expert's", "experts", "experts'", "expert"], "answer": 2},
      {"id": "u2-m084", "type": "mcq", "q": "Those are the ________ lockers. They park their bikes near them.", "options": ["boys'", "boy's", "boys", "boy"], "answer": 0},
      {"id": "u2-m085", "type": "mcq", "q": "Whose smart board is this? - It's the ________.", "options": ["school's", "school", "schools'", "schools"], "answer": 0},
      {"id": "u2-m086", "type": "mcq", "q": "The ________ library contains thousands of digital and paper e-books. (all the students)", "options": ["students'", "student's", "students", "student"], "answer": 0},
      {"id": "u2-m087", "type": "mcq", "q": "I can't read the ________ text because the paper is scratched.", "options": ["book's", "book", "books'", "books"], "answer": 0},
      {"id": "u2-m088", "type": "mcq", "q": "We found the ________ bag left in the computer studies classroom. (one professor)", "options": ["professor's", "professors", "professors'", "professor"], "answer": 0},
      {"id": "u2-m089", "type": "mcq", "q": "These are the ________ tools. They are testing the interactive platform.", "options": ["developers'", "developer's", "developers", "developer"], "answer": 0},
      {"id": "u2-m090", "type": "mcq", "q": "Setting achievable ________ motivates you to study harder every day.", "options": ["errors", "goals", "devices", "planners"], "answer": 1},
      {"id": "u2-m091", "type": "mcq", "q": "________ learning is excellent for students who live far away from school.", "options": ["Traditional", "Distance", "Slow", "Inactive"], "answer": 1},
      {"id": "u2-m092", "type": "mcq", "q": "It is highly recommended to ________ your old notes before the final exam.", "options": ["forget", "review", "drop", "lose"], "answer": 1},
      {"id": "u2-m093", "type": "mcq", "q": "Regular practice helps you develop your cognitive ________.", "options": ["skills", "tools", "devices", "routines"], "answer": 0},
      {"id": "u2-m094", "type": "mcq", "q": "Working in a group teaches us how to accept different ________.", "options": ["opinions", "clothes", "chargers", "mice"], "answer": 0},
      {"id": "u2-m095", "type": "mcq", "q": "The primary school ________ is very supportive to all young learners.", "options": ["headteacher", "driver", "doctor", "player"], "answer": 0},
      {"id": "u2-m096", "type": "mcq", "q": "These are the ________ project files. They are both digital engineers.", "options": ["men's", "mens'", "men", "mens"], "answer": 0},
      {"id": "u2-m097", "type": "mcq", "q": "My ________ advice guided me to choose the best learning strategy.", "options": ["mother's", "mothers'", "mother", "mothers"], "answer": 0},
      {"id": "u2-m098", "type": "mcq", "q": "The ________ screen is highly interactive and full of colors.", "options": ["tablet's", "tablet", "tablets'", "tablets"], "answer": 0},
      {"id": "u2-m099", "type": "mcq", "q": "Highlighting keywords is a powerful ________ to remember key concepts.", "options": ["mistake", "technique", "break", "password"], "answer": 1},
      {"id": "u2-m100", "type": "mcq", "q": "Students need to receive direct ________ from teachers to know their progress.", "options": ["feedback", "games", "snacks", "chargers"], "answer": 0},
      {"id": "u2-m101", "type": "mcq", "q": "Active participation in class discussions helps activate your ________.", "options": ["sleep", "memory", "time", "laptop"], "answer": 1},
      {"id": "u2-m102", "type": "mcq", "q": "This is the ________ office; she organizes the school timetable.", "options": ["supervisor's", "supervisor", "supervisors'", "supervisors"], "answer": 0},
      {"id": "u2-m103", "type": "mcq", "q": "The ________ dresses are prepared for the school theater play. (many girls)", "options": ["girls'", "girl's", "girls", "girl"], "answer": 0},
      {"id": "u2-m104", "type": "mcq", "q": "Whose digital planner is this? - It is ________.", "options": ["Ziads", "Ziad's", "Ziads'", "Ziad"], "answer": 1},
      {"id": "u2-m105", "type": "mcq", "q": "The ________ tools are kept in the maintenance garage.", "options": ["workmen's", "workmens'", "workmen", "workmens"], "answer": 0},
      {"id": "u2-m106", "type": "mcq", "q": "Time ________ is a vital skill that helps you avoid stress before exams.", "options": ["management", "break", "device", "password"], "answer": 0},
      {"id": "u2-m107", "type": "mcq", "q": "We have a fifteen-minute ________ after the third lesson to have a snack.", "options": ["break", "exam", "routine", "planner"], "answer": 0},
      {"id": "u2-m108", "type": "mcq", "q": "This is ________ digital tablet; she uses it to draw mind maps.", "options": ["Mona's", "Mona", "Monas'", "Monas"], "answer": 0},
      {"id": "u2-m109", "type": "mcq", "q": "The ________ engine needs to be fixed before the field trip tomorrow. (one bus)", "options": ["bus's", "bus", "buses'", "buses"], "answer": 0},
      {"id": "u2-m110", "type": "mcq", "q": "A visual mind map helps connect multiple ________ together easily.", "options": ["concepts", "clothes", "chargers", "mice"], "answer": 0},
      {"id": "u2-m111", "type": "mcq", "q": "Active learners always try to ________ new information with real life.", "options": ["link", "forget", "drop", "lose"], "answer": 0},
      {"id": "u2-m112", "type": "mcq", "q": "If you want to expand your English vocabulary, ________ daily.", "options": ["read", "sleep", "chat", "cry"], "answer": 0},
      {"id": "u2-m113", "type": "mcq", "q": "The ________ project was about the benefits of distance learning. (both twins)", "options": ["twins'", "twin's", "twins", "twin"], "answer": 0},
      {"id": "u2-m114", "type": "mcq", "q": "Teachers use simple language to make the learning process ________.", "options": ["harder", "easier", "slower", "worse"], "answer": 1},
      {"id": "u2-m115", "type": "mcq", "q": "Students should have a clean and well-lit study ________ at home.", "options": ["space", "device", "break", "mistake"], "answer": 0},
      {"id": "u2-m116", "type": "mcq", "q": "A digital planner is an effective tool to structure your ________.", "options": ["routine", "error", "password", "charger"], "answer": 0},
      {"id": "u2-m117", "type": "mcq", "q": "Working in a team encourages students to ________ with one another.", "options": ["collaborate", "fight", "sleep", "hide"], "answer": 0},
      {"id": "u2-m118", "type": "mcq", "q": "The ________ books are placed neatly on the classroom shelves.", "options": ["children's", "childrens'", "children", "childrens"], "answer": 0},
      {"id": "u2-m119", "type": "mcq", "q": "Making errors should be seen as a stepping stone to ________.", "options": ["failure", "success", "sleep", "damage"], "answer": 1},
      {"id": "u2-m120", "type": "mcq", "q": "I can't open the ________ cover; it is stuck.", "options": ["dictionary's", "dictionary", "dictionaries'", "dictionaries"], "answer": 0},
      {"id": "u2-m121", "type": "mcq", "q": "Good learners always remain ________ about discovering new scientific facts.", "options": ["lazy", "curious", "bored", "tired"], "answer": 1},
      {"id": "u2-m122", "type": "mcq", "q": "Online platforms give students access to various learning ________.", "options": ["resources", "clothes", "chargers", "passwords"], "answer": 0},
      {"id": "u2-m123", "type": "mcq", "q": "Look! The teacher ________ the new self-assessment strategy on the board.", "options": ["explains", "is explaining", "explain", "explained"], "answer": 1},
      {"id": "u2-m124", "type": "mcq", "q": "________ your friend have a regular study routine at home?", "options": ["Do", "Does", "Is", "Are"], "answer": 1},
      {"id": "u2-m125", "type": "mcq", "q": "We ________ study in noisy rooms because it ruins our focus.", "options": ["never", "always", "are", "is"], "answer": 0},
      {"id": "u2-m126", "type": "mcq", "q": "How often ________ you exchange notes with your school classmates?", "options": ["do", "does", "are", "is"], "answer": 0},
      {"id": "u2-m127", "type": "mcq", "q": "Listen! The headteacher ________ the names of top students now.", "options": ["calls", "is calling", "call", "called"], "answer": 1},
      {"id": "u2-m128", "type": "mcq", "q": "At present, they ________ a digital mind map for the history project.", "options": ["draw", "are drawing", "draws", "drew"], "answer": 1},
      {"id": "u2-m129", "type": "mcq", "q": "The sun ________ us light and energy every morning.", "options": ["give", "gives", "is giving", "giving"], "answer": 1},
      {"id": "u2-m130", "type": "mcq", "q": "Why ________ you reviewing this unit at this moment?", "options": ["do", "does", "are", "is"], "answer": 2},
      {"id": "u2-m131", "type": "mcq", "q": "Water ________ at 100 degrees Celsius. It's a proven fact.", "options": ["boil", "boils", "is boiling", "boiling"], "answer": 1},
      {"id": "u2-m132", "type": "mcq", "q": "What ________ your brother looking up in the online dictionary now?", "options": ["does", "is", "do", "are"], "answer": 1},
      {"id": "u2-m133", "type": "mcq", "q": "Modern students ________ like using traditional and boring techniques.", "options": ["doesn't", "don't", "aren't", "isn't"], "answer": 1},
      {"id": "u2-m134", "type": "mcq", "q": "I ________ prepare my study timetable before the school term begins.", "options": ["usually", "never", "rarely", "no"], "answer": 0},
      {"id": "u2-m135", "type": "mcq", "q": "Group workshops ________ enhance communication skills between pupils.", "options": ["always", "doesn't", "isn't", "aren't"], "answer": 0},
      {"id": "u2-m136", "type": "mcq", "q": "Look! The children ________ in pairs to solve the new puzzle.", "options": ["work", "are working", "works", "worked"], "answer": 1},
      {"id": "u2-m137", "type": "mcq", "q": "My father ________ checks his digital planner every Sunday morning.", "options": ["always", "never", "are", "is"], "answer": 0},
      {"id": "u2-m138", "type": "mcq", "q": "Does this application ________ interactive learning games?", "options": ["have", "has", "having", "is having"], "answer": 0},
      {"id": "u2-m139", "type": "mcq", "q": "A clever learner ________ forgets to check his exam feedback.", "options": ["never", "always", "usually", "often"], "answer": 0},
      {"id": "u2-m140", "type": "mcq", "q": "We shouldn't become completely dependent ________ digital applications.", "options": ["on", "at", "in", "for"], "answer": 0},
    ],
    correction: [
      {"id": "u2-c01", "type": "correction", "sentence": "This is the notebook of Tarek's.", "wrong": "Tarek's", "answers": ["Tarek"]},
      {"id": "u2-c02", "type": "correction", "sentence": "The students's project won the first prize.", "wrong": "students's", "answers": ["students'", "student's"]},
      {"id": "u2-c03", "type": "correction", "sentence": "I need to buy a computer's screen for my desk.", "wrong": "computer's", "answers": ["computer"]},
      {"id": "u2-c04", "type": "correction", "sentence": "Those are the childrens' drawings on the wall.", "wrong": "childrens'", "answers": ["children's"]},
      {"id": "u2-c05", "type": "correction", "sentence": "A good strategy is to forget your goals completely.", "wrong": "forget", "answers": ["remember", "set", "review", "follow", "keep", "achieve"]},
      {"id": "u2-c06", "type": "correction", "sentence": "The school bell rings to announce the break's.", "wrong": "break's", "answers": ["break"]},
      {"id": "u2-c07", "type": "correction", "sentence": "This is the cover of the book's.", "wrong": "book's", "answers": ["book"]},
      {"id": "u2-c08", "type": "correction", "sentence": "These are my brother's bags. They study in different universities.", "wrong": "brother's", "answers": ["brothers'"]},
      {"id": "u2-c09", "type": "correction", "sentence": "The mens' laboratory coats are in the room.", "wrong": "mens'", "answers": ["men's"]},
      {"id": "u2-c10", "type": "correction", "sentence": "A quiet space makes students feel very noisy.", "wrong": "noisy", "answers": ["calm", "relaxed", "comfortable", "peaceful", "focused", "concentrated"]},
      {"id": "u2-c11", "type": "correction", "sentence": "The car's door of the teacher is open.", "wrong": "car's", "answers": ["car"]},
      {"id": "u2-c12", "type": "correction", "sentence": "We find word meanings in the laboratory.", "wrong": "laboratory", "answers": ["dictionary"]},
      {"id": "u2-c13", "type": "correction", "sentence": "That is the laptop of Mr. Aly's.", "wrong": "Aly's", "answers": ["Aly"]},
      {"id": "u2-c14", "type": "correction", "sentence": "Reviewing your lessons helps you forget everything.", "wrong": "forget", "answers": ["remember", "recall", "memorize", "understand"]},
      {"id": "u2-c15", "type": "correction", "sentence": "The mind map is a traditional way to hide ideas.", "wrong": "hide", "answers": ["organize", "show", "link", "connect", "present", "arrange"]},
      {"id": "u2-c16", "type": "correction", "sentence": "This is the laptop of the student's.", "wrong": "student's", "answers": ["student"]},
      {"id": "u2-c17", "type": "correction", "sentence": "This is the notebook of the student's.", "wrong": "student's", "answers": ["student"]},
      {"id": "u2-c18", "type": "correction", "sentence": "The boys's project about time management was very useful.", "wrong": "boys's", "answers": ["boys'", "boy's"]},
      {"id": "u2-c19", "type": "correction", "sentence": "I can see the bicycles wheel near the laboratory.", "wrong": "bicycles", "answers": ["bicycle's"]},
      {"id": "u2-c20", "type": "correction", "sentence": "Those are the workmens' lab coats on the desk.", "wrong": "workmens'", "answers": ["workmen's"]},
      {"id": "u2-c21", "type": "correction", "sentence": "Challenging goals always make active students feel lazy.", "wrong": "lazy", "answers": ["motivated", "excited", "interested", "energetic", "encouraged", "curious", "enthusiastic"]},
      {"id": "u2-c22", "type": "correction", "sentence": "The school bell rings to show the end of the lesson's.", "wrong": "lesson's", "answers": ["lesson"]},
      {"id": "u2-c23", "type": "correction", "sentence": "This is the screen of the tablet's.", "wrong": "tablet's", "answers": ["tablet"]},
      {"id": "u2-c24", "type": "correction", "sentence": "These are my sister's notebooks. They study in different schools.", "wrong": "sister's", "answers": ["sisters'"]},
      {"id": "u2-c25", "type": "correction", "sentence": "The childrens' books are stored in the library room.", "wrong": "childrens'", "answers": ["children's"]},
      {"id": "u2-c26", "type": "correction", "sentence": "Constructive feedback helps us hide our learning mistakes.", "wrong": "hide", "answers": ["correct", "fix", "find", "understand", "improve", "see"]},
      {"id": "u2-c27", "type": "correction", "sentence": "The keyboard of my laptop's is working properly.", "wrong": "laptop's", "answers": ["laptop"]},
      {"id": "u2-c28", "type": "correction", "sentence": "Active students always sleep during class workshops.", "wrong": "sleep", "answers": ["participate", "work", "collaborate", "learn", "cooperate", "talk", "interact"]},
      {"id": "u2-c29", "type": "correction", "sentence": "That is the summary of Ahmed's.", "wrong": "Ahmed's", "answers": ["Ahmed"]},
      {"id": "u2-c30", "type": "correction", "sentence": "A study timetable is used to waste your preparation hours.", "wrong": "waste", "answers": ["organize", "manage", "plan", "structure", "use", "arrange", "save"]},
    ],
  };
})();
